import { describe, expect, it } from "vitest"
import { describeStreamError, retryable, retryAfterMs } from "@/core/agent"

describe("stream error handling", () => {
  it("describes a 429 rate limit clearly", () => {
    const error = Object.assign(new Error("Error from provider (Console): Rate limit exceeded. Please try again later."), { statusCode: 429 })
    const result = describeStreamError(error, "opencode-zen", "deepseek-v4-flash-free")
    expect(result.message).toContain("Rate limit exceeded")
    expect(result.message).toContain("opencode-zen/deepseek-v4-flash-free")
  })

  it("describes a 5xx server error", () => {
    const error = Object.assign(new Error("upstream"), { statusCode: 503 })
    const result = describeStreamError(error, "openrouter", "model")
    expect(result.message).toContain("server error")
    expect(result.message).toContain("HTTP 503")
  })

  it("falls back to a provider request-failed message for other errors", () => {
    const result = describeStreamError(new Error("boom"), "openai", "gpt-4.1")
    expect(result.message).toContain("openai request failed")
    expect(result.message).toContain("boom")
  })

  it("returns a clear message when the error carries no detail", () => {
    const result = describeStreamError(undefined, "openrouter", "model")
    expect(result.message).toContain("No output generated by openrouter/model")
  })

  it("treats NoOutputGeneratedError backed by a 429 as retryable", () => {
    const error = Object.assign(new Error("rate limited"), { name: "AI_NoOutputGeneratedError", statusCode: 429 })
    expect(retryable(error)).toBe(true)
  })

  it("treats a plain 429 as retryable", () => {
    expect(retryable(Object.assign(new Error("limit"), { statusCode: 429 }))).toBe(true)
  })

  it("does not retry a genuine empty stream without a provider status", () => {
    const error = Object.assign(new Error("No output generated. Check the stream for errors."), { name: "AI_NoOutputGeneratedError" })
    expect(retryable(error)).toBe(false)
  })

  it("reads a numeric Retry-After header as seconds", () => {
    const error = Object.assign(new Error("rate limited"), { statusCode: 429, headers: { "retry-after": "5" } })
    expect(retryAfterMs(error)).toBe(5000)
  })

  it("reads a decimal Retry-After header as milliseconds", () => {
    const error = Object.assign(new Error("rate limited"), { statusCode: 429, headers: { "retry-after": "0.25" } })
    expect(retryAfterMs(error)).toBe(250)
  })

  it("reads an HTTP-date Retry-After header", () => {
    const later = new Date(Date.now() + 3_000).toUTCString()
    const error = Object.assign(new Error("rate limited"), { statusCode: 429, headers: { "retry-after": later } })
    const value = retryAfterMs(error)
    expect(value).toBeGreaterThanOrEqual(2000)
    expect(value).toBeLessThanOrEqual(4000)
  })

  it("returns undefined when there is no Retry-After header", () => {
    expect(retryAfterMs(Object.assign(new Error("limit"), { statusCode: 429 }))).toBeUndefined()
  })
})
