import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"
import { resolveUnprotectedProjectPath } from "./project-path"

export interface FilesystemEntry { path: string; kind: "file" | "directory"; mode: number; contentBase64?: string }
export interface FilesystemSnapshot { version: 1; created: number; entries: FilesystemEntry[] }
function collect(root: string, full: string, output: FilesystemEntry[]) { const stat = lstatSync(full); const rel = relative(root, full).replaceAll("\\", "/"); if (stat.isSymbolicLink()) throw new Error(`Symbolic links cannot be snapshotted: ${rel}`); if (stat.isDirectory()) { output.push({ path: rel, kind: "directory", mode: stat.mode }); for (const name of readdirSync(full)) collect(root, join(full, name), output) } else if (stat.isFile()) output.push({ path: rel, kind: "file", mode: stat.mode, contentBase64: readFileSync(full).toString("base64") }); else throw new Error(`Unsupported filesystem entry: ${rel}`) }
export function captureFilesystemSnapshot(root: string, paths: string[]): FilesystemSnapshot { const entries: FilesystemEntry[] = []; for (const path of paths) { const target = resolveUnprotectedProjectPath(root, path).full; if (existsSync(target)) collect(resolve(root), target, entries) } return { version: 1, created: Date.now(), entries: entries.filter((entry, index, all) => all.findIndex((candidate) => candidate.path === entry.path) === index) } }
export function restoreFilesystemSnapshot(root: string, snapshot: FilesystemSnapshot, options: { removeUnlisted?: string[] } = {}) { const canonicalRoot = resolve(root); const temporary = join(canonicalRoot, ".nimbl", `restore-${crypto.randomUUID()}`); mkdirSync(temporary, { recursive: true }); try { for (const entry of snapshot.entries) { const target = resolveUnprotectedProjectPath(canonicalRoot, entry.path).full; const staged = join(temporary, entry.path); if (entry.kind === "directory") mkdirSync(staged, { recursive: true }); else { mkdirSync(dirname(staged), { recursive: true }); writeFileSync(staged, Buffer.from(entry.contentBase64 || "", "base64")); } chmodSync(staged, entry.mode & 0o7777) } for (const entry of snapshot.entries) { const target = resolveUnprotectedProjectPath(canonicalRoot, entry.path).full; const staged = join(temporary, entry.path); if (entry.kind === "directory") mkdirSync(target, { recursive: true }); else { mkdirSync(dirname(target), { recursive: true }); const backup = `${target}.nimbl-old-${crypto.randomUUID()}`; if (existsSync(target)) renameSync(target, backup); renameSync(staged, target); if (existsSync(backup)) rmSync(backup, { force: true }) } } for (const path of options.removeUnlisted || []) { const target = resolveUnprotectedProjectPath(canonicalRoot, path).full; if (existsSync(target)) rmSync(target, { recursive: true, force: true }) } } finally { rmSync(temporary, { recursive: true, force: true }) } }
